In [5]:
import numpy as np
import pandas as pd
import os
from sklearn.tree import DecisionTreeClassifier

In [3]:
#读文件预备动作
data_file=r'C:\Python\DM exercise\dm\chapter6\demo\data\model.xls'
o_data=pd.read_excel(data_file)

In [4]:
o_data

电量趋势下降指标  线损指标  告警类指标  是否窃漏电
0           4     1      1      1
1           4     0      4      1
2           2     1      1      1
3           9     0      0      0
4           3     1      0      0
5           2     0      0      0
6           5     0      2      1
7           3     1      3      1
8           3     0      0      0
9           4     1      0      0
10         10     1      2      1
11         10     1      3      1
12          2     0      3      0
13          4     0      2      0
14          3     0      0      0
15          0     0      3      0
16          9     0      3      1
17          0     0      2      0
18          8     1      4      1
19          2     0      4      0
20          3     0      1      0
21          7     0      0      0
22          6     0      0      0
23          4     1      2      1
24          7     0      0      0
25          2     1      0      0
26          5     1      0      0
27          1     1      4      1
28          5     1      1      1
29          1     0      2      0
..        ...   ...    ...    ...
261         5     1      2      0
262         2     0      2      0
263         5     0      0      0
264         2     0      2      0
265         2     0      0      0
266         3     1      2      0
267         5     1      0      0
268         4     1      2      0
269         1     0      1      0
270         4     0      2      0
271         2     1      1      0
272         1     1      2      0
273         1     0      0      0
274         2     1      1      0
275         3     0      1      0
276         0     1      1      0
277         0     1      0      0
278         0     1      1      0
279         1     0      1      0
280         2     0      2      0
281         3     0      2      0
282         4     0      0      0
283         2     1      0      0
284         3     1      2      0
285         3     0      1      0
286         4     1      2      0
287         1     0      2      0
288         5     1      2      1
289         2     1      0      0
290         4     1      0      0

[291 rows x 4 columns]

In [6]:
n=14
x=o_data.iloc[:,:3].as_matrix()
y=o_data.iloc[:,3].as_matrix()

from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=n)

dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

c:\users\yechao\appdata\local\programs\python\python35\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [7]:
from sklearn.externals import joblib
decision_tree_file=r'C:\Python\DM exercise\dm\chapter6\demo\data\tree.pkl'
joblib.dump(dt,decision_tree_file)

['C:\\Python\\DM exercise\\dm\\chapter6\\demo\\data\\tree.pkl']

In [20]:
y_pre=dt.predict(x_test)
y_pre

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [15]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [23]:
np.stack((y_pre,y_test)).T

array([[0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0,

In [ ]:
pre_n_real=pd.DataFrame(np.stack((y_pre,y_test)).T,columns=[u'预测',u'真实'])

In [25]:
pre_n_real

预测  真实
0    0   0
1    1   0
2    0   0
3    0   0
4    0   0
5    0   0
6    0   0
7    0   0
8    1   1
9    0   0
10   0   0
11   0   0
12   0   0
13   0   0
14   0   0
15   0   0
16   0   0
17   1   0
18   0   0
19   0   0
20   0   0
21   0   1
22   0   0
23   0   0
24   0   0
25   1   0
26   0   0
27   0   0
28   0   0
29   0   0
..  ..  ..
43   0   0
44   0   0
45   0   0
46   0   0
47   0   0
48   0   0
49   0   0
50   0   0
51   0   0
52   0   0
53   0   0
54   0   0
55   0   0
56   0   0
57   1   0
58   0   0
59   0   0
60   0   0
61   0   0
62   0   0
63   1   0
64   0   0
65   0   0
66   0   0
67   0   0
68   0   0
69   0   0
70   0   0
71   0   0
72   0   0

[73 rows x 2 columns]

In [33]:
matrix=pd.DataFrame(np.zeros([2,2],dtype=int))
matrix.index.name=u'预测'
matrix.columns.name=u'实际'
matrix

实际  0  1
预测      
0   0  0
1   0  0

In [44]:
pre_n_real[np.array(pre_n_real[u'预测']==0) & np.array(pre_n_real[u'真实']==0)]

预测  真实
0    0   0
2    0   0
3    0   0
4    0   0
5    0   0
6    0   0
7    0   0
9    0   0
10   0   0
11   0   0
12   0   0
13   0   0
14   0   0
15   0   0
16   0   0
18   0   0
19   0   0
20   0   0
22   0   0
23   0   0
24   0   0
26   0   0
27   0   0
28   0   0
29   0   0
30   0   0
31   0   0
32   0   0
33   0   0
34   0   0
..  ..  ..
41   0   0
42   0   0
43   0   0
44   0   0
45   0   0
46   0   0
47   0   0
48   0   0
49   0   0
50   0   0
51   0   0
52   0   0
53   0   0
54   0   0
55   0   0
56   0   0
58   0   0
59   0   0
60   0   0
61   0   0
62   0   0
64   0   0
65   0   0
66   0   0
67   0   0
68   0   0
69   0   0
70   0   0
71   0   0
72   0   0

[65 rows x 2 columns]

In [45]:
for i in range(2):
    for j in range(2):
        matrix.iloc[i,j]=len(pre_n_real[np.array(pre_n_real[u'预测']==i) & np.array(pre_n_real[u'真实']==j)])

In [46]:
matrix

实际   0  1
预测       
0   65  1
1    5  2

In [49]:
matrix.to_excel(r'C:\Python\DM exercise\dm\chapter6\demo\data\matrix.xls')