In [2]:
import numpy as np
import pandas as pd

In [4]:
data_file=r'C:\Python\DM exercise\dm\chapter11\拓展思考\拓展思考样本数据.xls'
data=pd.read_excel(data_file)

In [8]:
data=data.set_index(data[u'日期']).drop([u'日期'],axis=1)
data

CPU告警  内存告警  磁盘告警  日志类告警  表空间告警  PING告警  telnet告警  故障类别
日期                                                                 
2013-01-01      4     1     0      0      0       2         4     0
2013-01-02      0     2     0      0      0       0         0     0
2013-01-03      1     0     0      0      0       0         2     0
2013-01-04      0     0     0      0      0       1         2     1
2013-01-05      1     0     0      2      0       4         0     1
2013-01-06      1     1     0      0      0       3         4     0
2013-01-07      1     0     0      0      0       0         0     0
2013-01-08      1     2     0      0      0       0         2     0
2013-01-09      0     0     0      0      0       1         0     0
2013-01-10      3     0     0      2      0       4         0     1
2013-01-11      0     1     0      0      0       3         4     0
2013-01-12      3     1     0      0      0       0         0     0
2013-01-13      0     0     0      0      0       0         2     0
2013-01-14      5     1     0      0      0       1         0     0
2013-01-15      0     0     0      0      0       4         0     0
2013-01-16      1     0     0      1      0       2         4     1
2013-01-17      0     2     0      0      0       0         0     0
2013-01-18      2     2     0      0      0       0         2     0
2013-01-19      0     0     0      0      0       0         0     0
2013-01-20      0     1     0      0      0       4         0     0
2013-01-21      0     0     0      0      0       3         3     0
2013-01-22      1     0     0      0      0       0         0     0
2013-01-23      0     0     0      0      0       0         2     0
2013-01-24      0     3     0      0      0       0         0     0
2013-01-25      0     0     0      0      0       4         0     0
2013-01-26      0     2     0      0      0       2         4     0
2013-01-27      0     0     0      0      0       0         0     0
2013-01-28      0     0     0      0      0       0         2     0
2013-01-29      0     2     0      0      0       1         1     1
2013-01-30      0     2     0      2      0       4         0     1
...           ...   ...   ...    ...    ...     ...       ...   ...
2013-12-02      0     6     4      3      3       2         3     2
2013-12-03      6     1     4      0      5       0         0     0
2013-12-04      0     1     5      0      5       0         2     0
2013-12-05      0     2     6      0      2       0         0     0
2013-12-06      0     2     6      3      4       4         0     2
2013-12-07      3     0     5      0      3       3         3     0
2013-12-08      2     3     3      1      4       0         0     1
2013-12-09      1     2     3      2      1       0         2     2
2013-12-10      0     1     7      2      8       1         0     1
2013-12-11      2     3     6      0      2       4         0     0
2013-12-12      5     0     7      0      9       2         4     0
2013-12-13      3     1     6      0      3       0         0     0
2013-12-14      0     0     8      0      8       0         2     0
2013-12-15      5     0     1      2      0       0         0     2
2013-12-16      5     0     8      2      4       4         0     1
2013-12-17      2     4     6      0      5       3         4     0
2013-12-18      1     2     4      0      8       0         1     0
2013-12-19      2     0     2      0      3       0         2     0
2013-12-20      0     5     4      3      3       1         0     2
2013-12-21      1     0     5      0      7       4         0     0
2013-12-22      3     0     3      0      7       2         4     0
2013-12-23      3     3     5      0      3       0         1     1
2013-12-24      1     6     5      0      6       0         2     1
2013-12-25      2     0     4      0      3       2         2     1
2013-12-26      0     6     2      0      6       4         0     0
2013-12-27      3     2     2      1      6       1         4     2


In [9]:
#http://blog.csdn.net/bryan__/article/details/51607215 这个帖子非常全面

In [13]:
#相关性分析，相关系数越靠近0越不相关，并不能用此判断，原因是故障类别的编号无意义，而计量数据可以
data.corr(method='pearson')[u'故障类别']

CPU告警       0.063104
内存告警        0.153468
磁盘告警        0.064091
日志类告警       0.797829
表空间告警       0.093983
PING告警      0.129593
telnet告警   -0.009152
故障类别        1.000000
Name: 故障类别, dtype: float64

In [19]:
#主成分分析，方差跟整体方差没有多大差距，这样的特征也被称为主成分，本质计算特征之间的相关性，适用于连续属性,只需要X
from sklearn.decomposition import PCA
n=7
x=data.iloc[:,:7]
pca=PCA(n_components=n)
xd=pca.fit_transform(x)

pca.explained_variance_ratio_

array([ 0.40858926,  0.15727096,  0.13548189,  0.11889294,  0.10104375,
        0.04137721,  0.03734399])

In [47]:
#以下代码是被转换过的主成分，所以除了图像识别等，有解释性需求的筛选最好别用
n=5
x=data.iloc[:,:7]
pca=PCA(n_components=n)
xd=pca.fit_transform(x)
# low_3=pd.DataFrame(xd)
low_3=pca.inverse_transform(xd)
low_3

array([[  4.00199676e+00,   9.43290591e-01,   5.07164310e-02, ...,
         -3.99510781e-02,   1.94597305e+00,   3.99226089e+00],
       [ -1.77152102e-04,   1.95386453e+00,  -4.65353082e-02, ...,
          4.53605367e-02,  -4.50637222e-02,   3.02898283e-04],
       [  1.00129325e+00,  -2.45920080e-02,   4.28187799e-02, ...,
         -3.57942542e-02,  -2.31653332e-02,   1.99507862e+00],
       ..., 
       [  9.83624772e-01,   5.90092645e+00,   5.12061168e+00, ...,
          5.78868072e+00,  -1.06631539e-01,   2.05923699e+00],
       [  1.34013784e-02,   1.87324827e-01,   2.80696956e+00, ...,
          3.26772107e+00,   1.19079067e+00,  -4.76824122e-02],
       [ -1.96862231e-02,   2.89125579e+00,   5.95131590e+00, ...,
          6.93968032e+00,   3.88190438e+00,   7.12921422e-02]])

In [41]:
#KBest x,y都需要
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import mutual_info_classif

x=data.iloc[:,:7]
y=data.iloc[:,7]


In [81]:
'''
卡方检验就是统计样本的实际观测值与理论推断值之间的偏离程度
卡方值越大，越不符合；卡方值越小，偏差越小，越趋于符合，若两个值完全相等时，卡方值就为0
返回：特征统计和特征P值 
可以用于判断分类变量的得分
'''
chi2(x,y) 

(array([  7.96424664e+00,   1.54984338e+01,   7.37590932e+00,
          3.21488271e+02,   1.11598245e+01,   1.07339474e+01,
          8.81294703e-02]),
 array([  1.86460059e-02,   4.31079977e-04,   2.50231306e-02,
          1.54777905e-70,   3.77289659e-03,   4.66823734e-03,
          9.56892011e-01]))

In [115]:
a=chi2(x,y)[1]
a=list(a)
b=sorted(a)
print(a)
print(b)#按照p值，特征重要度排序为：4-2-5-6-1，其中4显著其余雷同

[0.018646005877863591, 0.00043107997669051233, 0.02502313058290934, 1.5477790538050752e-70, 0.0037728965853833147, 0.004668237342632402, 0.95689201091292542]
[1.5477790538050752e-70, 0.00043107997669051233, 0.0037728965853833147, 0.004668237342632402, 0.018646005877863591, 0.02502313058290934, 0.95689201091292542]


In [37]:
f_classif(x,y) #选F值大或P小，肉眼看排序，特征4显著地大
'''
其通常是用来分析用了超过一个参数的统计模型，以判断该模型中的全部或一部分参数是否适合用来估计母体
返回：特征F值，特征P值
可以用于判断分类变量的得分
'''

(array([  1.98029799e+00,   5.22805152e+00,   1.37112722e+00,
          3.18469304e+02,   2.00272278e+00,   3.09373086e+00,
          2.70144845e-02]),
 array([  1.39520565e-01,   5.77642415e-03,   2.55135639e-01,
          1.62079747e-80,   1.36459964e-01,   4.65332283e-02,
          9.73349105e-01]))

In [39]:
mutual_info_classif(x,y)
'''

'''

array([ 0.0387362 ,  0.02450917,  0.        ,  0.43848975,  0.        ,
        0.        ,  0.01827571])

In [54]:
#通过评分函数选择
n=3
x_selected1=SelectKBest(chi2,k=n).fit_transform(x,y)
x_selected2=SelectKBest(f_classif,k=n).fit_transform(x,y)

In [58]:
#单变量特征选择之决策树归纳，适合非线性关系的数据
'''
from sklearn.cross_validation import cross_val_score, ShuffleSplit  
from sklearn.datasets import load_boston  
from sklearn.ensemble import RandomForestRegressor  
  
#Load boston housing dataset as an example  
boston = load_boston()  
X = boston["data"]  
Y = boston["target"]  
names = boston["feature_names"]  
  
rf = RandomForestRegressor(n_estimators=20, max_depth=4)  
scores = []  
for i in range(X.shape[1]):  
     score = cross_val_score(rf, X[:, i:i+1], Y, scoring="r2",  
                              cv=ShuffleSplit(len(X), 3, .3))  
     scores.append((round(np.mean(score), 3), names[i]))  
print sorted(scores, reverse=True)  

[(0.636, ‘LSTAT’), (0.59, ‘RM’), (0.472, ‘NOX’), (0.369, ‘INDUS’), (0.311, ‘PTRATIO’), (0.24, ‘TAX’), (0.24, ‘CRIM’), (0.185, ‘RAD’), (0.16, ‘ZN’), (0.087, ‘B’), (0.062, ‘DIS’), (0.036, ‘CHAS’), (0.027, ‘AGE’)]
'''
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()

In [ ]:
#SelectFromModel

In [116]:
#SelectFromModel--svm.LinearSVC
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import LinearSVC
lsvc=LinearSVC(C=0.01,penalty='l1',dual=False).fit(x,y)
model=SelectFromModel(lsvc,prefit=True)
x_new=model.transform(x)
x_new.shape

(365, 5)

In [70]:
#SelectFromModel--tree
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
clf = ExtraTreesClassifier().fit(x, y)
clf.feature_importances_  
'''
这里的重要度排序是-4-1-7-2-6
上面的KBest排序用chi2/f检验根据试K，都是-4-2-6-1
观察P值，4显著大，4-2-5-6-1
'''

array([ 0.12769848,  0.09385279,  0.06431308,  0.44839483,  0.07295663,
        0.0927713 ,  0.1000129 ])

In [1]:
#正则化：正则化就是把额外的约束或者惩罚项加到已有模型（损失函数）上，以防止过拟合并提高泛化能力。
#一般是L1或者L2范数，alpha是一个可调的参数，控制着正则化的强度。当用在线性模型上时，L1正则化和L2正则化也称为Lasso和Ridge
#L1正则化将系数w的l1范数作为惩罚项加到损失函数上，由于正则项非零，这就迫使那些弱的特征所对应的系数变成0。因此L1正则化往往会使学到的模型很稀疏（系数w经常为0），这个特性使得L1正则化成为一种很好的特征选择方法。
#Scikit-learn为线性回归提供了Lasso，为分类提供了L1逻辑回归
#L2正则化对于特征选择来说一种稳定的模型，不像L1正则化那样，系数会因为细微的数据变化而波动。所以L2正则化和L1正则化提供的价值是不同的，L2正则化对于特征理解来说更加有用：表示能力强的特征对应的系数是非零。
'''
from sklearn.linear_model import Lasso  
from sklearn.preprocessing import StandardScaler  
from sklearn.datasets import load_boston  
  
boston = load_boston()  
scaler = StandardScaler()  
X = scaler.fit_transform(boston["data"])  
Y = boston["target"]  
names = boston["feature_names"]  
  
lasso = Lasso(alpha=.3)  
lasso.fit(X, Y)  
  
print ("Lasso model: ", pretty_print_linear(lasso.coef_, names, sort = True))  
'''