In [ ]:
#交叉验证
from  sklearn.model_selection  import  train_test_split 
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=0)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, iris.data, iris.target, cv=5, scoring='f1_macro') 
#http://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter ，scoring的类型
scores.mean()

#交叉验证的每次随机选验证集版本，会重复
from sklearn.model_selection import ShuffleSplit
cv = ShuffleSplit(n_splits=3, test_size=0.3, ，train_size = ，random_state=0)
for train_index, test_index in cv.split(X):

In [ ]:
#多分数交叉验证
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
scoring = ['precision_macro', 'recall_macro']
scores = cross_validate(clf, iris.data, iris.target, scoring=scoring,cv=5, return_train_score=False)
sorted(scores.keys())
scores['test_recall_macro']

from sklearn.metrics.scorer import make_scorer #自定义评分和字典from sklearn.model_selection import cross_val_predict
scoring = {'prec_macro': 'precision_macro','rec_micro': make_scorer(recall_score, average='macro')}

In [ ]:
#为数据集做预测
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf, X, y)

In [ ]:
KFold
RepeatedKFold
LeaveOneOut #只有一个样本作为测试集，5或10倍交叉验证应优于LOO
lpo = LeavePOut(p=2)

In [ ]:
#样本类别不平衡需要分层抽取测试集
from sklearn.model_selection import StratifiedKFold
RepeatedStratifiedKFold
StratifiedShuffleSplit

In [ ]:
#按照组别划分
GroupKFold
gkf = GroupKFold(n_splits=3) #同一组拆分到一起
gkf.split(X, y, groups=groups)

LeaveOneGroupOut
LeavePGroupsOut
GroupShuffleSplit

In [ ]:
#时间序列交叉验证,
from sklearn.model_selection import TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits=3)
for train, test in tscv.split(X):

In [8]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4],[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])
tscv = TimeSeriesSplit(n_splits=3)
print(tscv)  

for train, test in tscv.split(X):
    print("%s %s" % (train, test))

TimeSeriesSplit(max_train_size=None, n_splits=3)
[0 1 2] [3 4 5]
[0 1 2 3 4 5] [6 7 8]
[0 1 2 3 4 5 6 7 8] [ 9 10 11]


In [ ]:
#超参数：参数空间搜索，样本选择，交叉验证和打分
estimator.get_params() #返回估计器的参数值

#GridSearchCV
param_grid
param_grid = [
  {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},]
#两个网格
scores = ['precision', 'recall']
clf = GridSearchCV(SVC(), tuned_parameters, cv=5,
                       scoring='%s_macro' % score) #for
#多个打分，分数名字/分数函数
scoring = {'AUC': 'roc_auc', 'Accuracy': make_scorer(accuracy_score)} #字典，在cv_results_中会有打分名称的标识
scoring = scoring
#方法：会继承估计器的
clf.fit(X_train, y_train)
clf.best_params_
best_estimator_
best_score_
#clf.cv_results_包括一堆
means = clf.cv_results_['mean_test_score']
stds = clf.cv_results_['std_test_score']
clf.cv_results_['params']
clf.predict(X_test)


#RandomizedSearchCV 可以写连续范围，随机抽样
param_distributions
param_distributions={'C': scipy.stats.expon(scale=100), 'gamma': scipy.stats.expon(scale=.1),
  'kernel': ['rbf'], 'class_weight':['balanced', None]}
#参数
n_iter #参数采样的数量


#某些模型特定的参数搜多和交叉验证
linear_model.LassoCV
linear_model.ElasticNetCV
linear_model.RidgeCV
#还有集成学习的包等

In [ ]:
#模型评估：估计器或交叉验证的分数/metrics库提供的实现特定目的的评估，metrics定制自己的评分函数
#1.非默认值定制
from sklearn.metrics import fbeta_score, make_scorer
ftwo_scorer = make_scorer(fbeta_score, beta=2)
#2.完全定制：例如定制混淆矩阵
X, y = datasets.make_classification(n_classes=2, random_state=0)
svm = LinearSVC(random_state=0)
def tp(y_true, y_pred): return confusion_matrix(y_true, y_pred)[0, 0]
def tn(y_true, y_pred): return confusion_matrix(y_true, y_pred)[0, 0]
def fp(y_true, y_pred): return confusion_matrix(y_true, y_pred)[1, 0]
def fn(y_true, y_pred): return confusion_matrix(y_true, y_pred)[0, 1]
scoring = {'tp' : make_scorer(tp), 'tn' : make_scorer(tn),
           'fp' : make_scorer(fp), 'fn' : make_scorer(fn)}
cv_results = cross_validate(svm.fit(X, y), X, y, scoring=scoring)


#classification_report不同类别的分类报告
target_names = ['class 0', 'class 1', 'class 2']
classification_report(y_true, y_pred, target_names=target_names)


precision_score和recall_score
#多分类的F1召回准确率问题：
precision_score
recall_score
f1_score
average='micro' #设置多分类的计算方式


#铰链损失：用于最大边缘分类器，如SVM，单侧
hinge_loss 

#Log loss，逻辑回归损失

#roc_curve 

In [ ]:
sklearn.dummy.DummyClassifier#简单预测和简单回归，为了对比一些最原始的分类器可估计器的差别
stratified 通过尊重训练集类分布来生成随机预测。
most_frequent 总是预测训练集中最常见的标签。
prior总是预测课程最大化之前的课程（如返回班级之前。most_frequent`) and ``predict_proba
uniform 随机产生预测。
constant 总是预测用户提供的常量标签。

In [ ]:
#分类器的保存
import pickle
s = pickle.dumps(clf) #变量
clf2 = pickle.loads(s)

#带着大量numpy数组时用joblib
from sklearn.externals import joblib
joblib.dump(clf, 'filename.pkl')  #文件

In [ ]:
#验证曲线：验证单个超参数对模型得分（训练和测试集）的曲线
train_scores, valid_scores = validation_curve(Ridge(), X, y, "alpha",np.logspace(-7, 3, 3))
validation_curve(estimator, X, y, param_name, param_range,)

#学习曲线：验证样本数量对模型得分的曲线
#随着样本的增大，训练集得分降低，测试集增高，随后逐渐接近
train_sizes, train_scores, valid_scores = learning_curve(
    SVC(kernel='linear'), X, y, train_sizes=[50, 80, 110], cv=5)

#学习曲线像是没什么谱的时候的一种估计，找一个还凑活的先试试