In [5]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import Ridge

n=14
boston = load_boston() 
x = boston["data"]  
y = boston["target"] 
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=n)

c:\users\yechao\appdata\local\programs\python\python35\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
ridge = Ridge(alpha=10)  
ridge.fit(x_train,y_train)

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [7]:
ridge.coef_

array([ -8.86257006e-02,   5.14080783e-02,  -4.02609472e-02,
         1.63243459e+00,  -1.72102573e+00,   4.05224571e+00,
        -1.02753608e-03,  -1.12306415e+00,   2.98090749e-01,
        -1.52873790e-02,  -8.04084596e-01,   6.54165312e-03,
        -6.03621778e-01])

In [8]:
ridge.intercept_ #截距

25.927692488000574

In [11]:
ridge.predict(x_test)

array([ 18.8831508 ,  40.18851093,  23.82156127,  24.37754622,
        21.2198702 ,  22.35854864,  12.15665946,   3.86245059,
        19.1521529 ,  15.87735581,  23.84215435,  21.00049716,
        16.49873066,  24.38870597,  22.71650145,  32.72496019,
        35.08628688,  20.63092124,  17.10321056,  26.8705898 ,
        18.68587169,  31.23617694,   0.56335542,  14.96499933,
         8.68949965,  16.64031211,  20.35199252,  20.30307999,
        22.75163287,  25.88758079,  22.92505851,  26.81064022,
        26.33405017,  23.03322337,  28.20563167,  33.21641659,
         8.97311825,  17.95355135,  18.08520024,  16.28966831,
        34.65269502,  26.13385149,  20.12834074,  23.72093834,
        17.28687051,  21.19402774,  24.85670041,  20.13810331,
        20.07465554,  12.47916718,  19.46541215,  15.06633575,
         9.92804695,  26.02102734,   5.18910043,  14.20680329,
        15.88381894,  13.71979179,  22.96349822,  -1.79443861,
        20.65143494,  33.75286158,  22.88317786,  32.38

In [9]:
from sklearn.linear_model import RidgeCV #通过
reg = RidgeCV(alphas=[0.1, 1.0, 10.0])
reg.fit(x_train,y_train)

RidgeCV(alphas=[0.1, 1.0, 10.0], cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)

In [10]:
reg.alpha_

0.10000000000000001

In [11]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import LassoCV
from sklearn.linear_model import LassoLarsCV
#参数http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html#sklearn.linear_model.LassoCV

reg3 = LassoCV(alphas=[0.1, 1.0, 10.0]) #最重要的参数：n_alphas=100, alphas=None
reg3.fit(x_train,y_train)
reg3.alpha_ #最重要的方法

0.10000000000000001

In [12]:
#估计器LassoLarsIC建议使用Akaike信息标准（AIC）和贝叶斯信息准则（BIC）
#MultiTaskLasso联合估计多个稀疏系数
#弹性网——l1和l2正则的结合，只有少量非零项同时也有岭回归的稳定性 ElasticNet，ElasticNetCV 

In [15]:
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import ElasticNetCV

reg2=ElasticNet(alpha=1.0, l1_ratio=0.5) #默认值。``alpha = 0``相当于普通最小二乘法，l1_ratio表示比例
reg2.fit(x_train,y_train)
reg2.coef_

array([-0.06940358,  0.05754054, -0.03729362,  0.        , -0.        ,
        1.09796559,  0.03445629, -0.6449193 ,  0.32699111, -0.01781883,
       -0.76296872,  0.00467941, -0.81171403])

In [16]:
reg2.predict(x_test)

array([ 23.21031741,  34.71800857,  24.23696403,  23.53268064,
        20.86597162,  24.32869381,  13.68482101,   3.34510626,
        18.30398073,  16.11423434,  23.12068799,  21.5492641 ,
        15.90066025,  24.52743877,  23.84200609,  32.65015718,
        30.94980445,  21.18531971,  13.82833989,  28.64754667,
        18.81501955,  30.94800929,  -0.04056094,  17.24206171,
         9.60750014,  15.45276143,  21.89680246,  20.64992236,
        23.11721174,  27.12482213,  25.24801759,  26.65816681,
        26.46137822,  23.98373075,  28.18609131,  31.99677355,
         5.89238744,  15.67273083,  21.62333027,  20.62587867,
        31.41318464,  27.97604018,  22.15830792,  24.19496469,
        16.17297329,  23.11738824,  26.01251374,  21.86818148,
        19.77296565,  10.19267025,  19.68089922,  15.92885883,
         7.11253633,  24.87851606,   7.22321056,  15.81966889,
        15.88226639,  10.22360541,  23.87968252,  -0.5845246 ,
        20.78536468,  33.57206706,  23.021927  ,  31.25

In [19]:
reg2.score(x_test,y_test) #返回预测的R^2打分

0.57327981195608146

In [21]:
'''
ElasticNetCV 交叉验证得到alpha和l1_ratio的最佳值
ElasticNetCV（l1_ratio = 0.5，eps = 0.001，n_alphas = 100，alphas = None，cv = None
l1_ratio传测试数组或单数
eps路径长度
alphas待测列表
cv交叉验证生成器/N倍折叠
'''
from sklearn.linear_model import ElasticNetCV
reg4 = ElasticNetCV(cv=5, random_state=0)
reg4.fit(x_train,y_train)
reg4.alpha_

1.4380529806949267

In [22]:
reg4.l1_ratio_

0.5

In [23]:
reg4.coef_

array([-0.05983194,  0.05712568, -0.02571127,  0.        , -0.        ,
        0.69947521,  0.04120264, -0.4889974 ,  0.3079982 , -0.01750324,
       -0.70737226,  0.00439763, -0.83567378])

In [25]:
reg4.score(x_test,y_test)

0.5617857355053022

In [26]:
reg4.alphas_

array([  1.43805298e+03,   1.34113302e+03,   1.25074515e+03,
         1.16644911e+03,   1.08783434e+03,   1.01451795e+03,
         9.46142835e+02,   8.82375974e+02,   8.22906787e+02,
         7.67445624e+02,   7.15722357e+02,   6.67485066e+02,
         6.22498806e+02,   5.80544470e+02,   5.41417716e+02,
         5.04927974e+02,   4.70897518e+02,   4.39160602e+02,
         4.09562647e+02,   3.81959495e+02,   3.56216704e+02,
         3.32208890e+02,   3.09819123e+02,   2.88938351e+02,
         2.69464873e+02,   2.51303842e+02,   2.34366805e+02,
         2.18571266e+02,   2.03840295e+02,   1.90102141e+02,
         1.77289893e+02,   1.65341147e+02,   1.54197707e+02,
         1.43805298e+02,   1.34113302e+02,   1.25074515e+02,
         1.16644911e+02,   1.08783434e+02,   1.01451795e+02,
         9.46142835e+01,   8.82375974e+01,   8.22906787e+01,
         7.67445624e+01,   7.15722357e+01,   6.67485066e+01,
         6.22498806e+01,   5.80544470e+01,   5.41417716e+01,
         5.04927974e+01,

In [ ]:
# MultiTaskElasticNet 联合估计多个回归问题的稀疏系数
#最小角度回归
#正交匹配追踪

In [ ]:
#贝叶斯回归：在学习中估计正则参数，但不是CV，不耗时用全数据集，假设Y遵循高斯分布，同时更复杂
#带有参数估计的问题都能用贝叶斯，别人计算最优化的准确值，贝叶斯计算未知参数的分布情况
from sklearn.linear_model import BayesianRidge
reg5 = linear_model.BayesianRidge()
reg.fit(x_train,y_train)

In [29]:
'''
逻辑回归:LogisticRegression（penalty ='l2'，dual = False，tol = 0.0001，C = 1.0，solver ='liblinear',multi_class ='ovr '
multi_class ='ovr ' 默认一对多分类，multinomial，多项式
solver =“liblinear”（默认，二分类小数据），“newton-cg”（仅l2），“lbfgs”（仅l2），“sag”（仅l2）和“saga”（通常最好）罚项支持不同
'''
from sklearn.linear_model import LogisticRegression
X=[[1,0],[1,1]]
Y=[1,0]
reg6=LogisticRegression()
reg6.fit(X,Y)
reg6.predict([[0,0]])

array([1])

In [33]:
reg6.predict_proba([[0,0]]) #概率

array([[ 0.48691094,  0.51308906]])

In [34]:
reg6.score(X,Y) #测试集分数

1.0

In [ ]:
# linearsvc:与参数kernel ='linear'的SVC类似，但是以liblinear而不是libsvm来实现
from sklearn.svm import LinearSVC
reg7=LinearSVC(penalty=’l2’, loss=’squared_hinge’, dual=True, tol=0.0001, C=1.0, multi_class=’ovr’)
# loss指定丢失函数   Prefer dual=False when n_samples > n_features即低维
reg7.predict
reg7.score

In [ ]:
#随机梯度下降 SGD，分为SGDClassifier和SGDRegressor，使用不同的损失函数和不同惩罚进行分类和回归
#该估计器实现了具有随机梯度下降（SGD）学习的正则化线性模型：每次估计一个样本的损失梯度，并且模型随着强度递减（也称为学习率）更新。
#单个训练样本来逼近真实梯度，优点：效率，缺点：对特征缩放很敏感，所以要标准化

#SGDClassifier
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss="hinge", penalty="l2"alpha= 0.0001，l1_ratio = 0.15，learning_rate='invscaling'，average=True)
#loss="hinge"线性SVM“log”损失给出逻辑回归，概率分类器
#penalty='none'，'l2'，'l1'或'elasticnet'

In [ ]:
#SGDRegressor：非常适合回归问题具有大量训练样本，（> 10.000），否则用lasso等
from sklearn.linear_model import SGDRegressor
clf = SGDRegressor (loss== 'squared_loss' , penalty="l2"alpha= 0.0001，l1_ratio = 0.15，learning_rate='invscaling')
clf.average_coef_ #平均权重
#loss=“squared_loss”(最小二乘法拟合)，“huber”，“epsilon_insensitive”（线性支持向量机回归）或“squared_epsilon_insensitive”

In [ ]:
#鲁棒性回归：在有异常值和错误时拟合模型，高维特征拟合困难
#3个鲁棒的回归估计： RANSAC， Theil Sen和 HuberRegressor

# RANSAC：随机样本子集--残差--小残差内部集
#Theil Sen：中位数回归
#HuberRegressor：不同于前两者，它不会忽视离群值的影响，而是给予它们更小的权重，如果该样本的绝对误差小于某个阈值，则样本被归类为一个惰性

In [ ]:
#多项式回归：不线性转变为线性
from sklearn.preprocessing import PolynomialFeatures
p=PolynomialFeatures （degree = 3 ）
p.fit_transform(x)

In [ ]:
'''
线性模型的要求是XY有线性关系而X自身不能线性相关，多项式
'''